<?php

use App\Http\Controllers\BusinessController as B;
use App\Http\Controllers\MasterController as M;
use App\Http\Controllers\PlatformController as P;
use App\Http\Controllers\PosController as Pos;
use App\Http\Controllers\RecurringExpenseController as Regular;
use App\Http\Controllers\ReportController as R;
use App\Http\Controllers\WorkflowController as Workflow;
use Illuminate\Support\Facades\Route;

Route::prefix('api')->middleware(['auth:sanctum', 'auth:tenant'])->group(function () {
    Route::get('me', [B::class, 'me']);
    Route::middleware('verified')->group(function () {
        Route::get('businesses', [B::class, 'businesses'])->name('businesses.index');
        Route::post('businesses', [B::class, 'createBusiness'])->name('businesses.store');
        Route::post('invitations/{token}', [M::class, 'acceptInvitation'])->name('invitations.accept');
        Route::prefix('app/{tenant}')->middleware('tenant.context')->name('app.')->group(function () {
            Route::get('/', [R::class, 'dashboard'])->name('dashboard');
            Route::get('lookup', [M::class, 'lookup']);
            Route::get('workflows', [Workflow::class, 'listing']);
            Route::post('workflows', [Workflow::class, 'save']);
            Route::get('workflow/{id}', [Workflow::class, 'show'])->whereNumber('id');
            Route::patch('workflow/{id}', [Workflow::class, 'save'])->whereNumber('id');
            Route::post('workflow/{id}/status', [Workflow::class, 'status'])->whereNumber('id');
            Route::post('workflow/{id}/order', [Workflow::class, 'order'])->whereNumber('id');
            Route::post('workflow/{id}/bill', [Workflow::class, 'bill'])->whereNumber('id');
            Route::get('pos/config', [Pos::class, 'config']);
            Route::patch('pos/profile', [Pos::class, 'profile']);
            Route::post('pos/branches', [Pos::class, 'branch']);
            Route::post('pos/resources', [Pos::class, 'resource']);
            Route::patch('pos/resources/{id}', [Pos::class, 'resource'])->whereNumber('id');
            Route::post('pos/preview', [Pos::class, 'preview']);
            Route::post('pos/sales', [Pos::class, 'sale']);
            Route::get('restaurant/orders', [Pos::class, 'orders']);
            Route::post('restaurant/orders', [Pos::class, 'order']);
            Route::post('restaurant/orders/{id}/send', [Pos::class, 'send'])->whereNumber('id');
            Route::post('restaurant/orders/{id}/tickets/{ticket}', [Pos::class, 'ticket'])->whereNumber('id')->whereNumber('ticket');
            Route::post('restaurant/orders/{id}/cancel', [Pos::class, 'cancelOrder'])->whereNumber('id');
            Route::post('restaurant/orders/{id}/checkout', [Pos::class, 'orderCheckout'])->whereNumber('id');
            Route::get('appointments', [Pos::class, 'bookings']);
            Route::post('appointments', [Pos::class, 'booking']);
            Route::post('appointments/{id}', [Pos::class, 'updateBooking'])->whereNumber('id');
            Route::post('appointments/{id}/checkout', [Pos::class, 'bookingCheckout'])->whereNumber('id');
            Route::get('regular-expenses', [Regular::class, 'listing']);
            Route::post('regular-expenses', [Regular::class, 'save']);
            Route::get('regular-expenses/{id}', [Regular::class, 'show'])->whereNumber('id');
            Route::patch('regular-expenses/{id}', [Regular::class, 'save'])->whereNumber('id');
            Route::get('regular-expenses/{id}/period', [Regular::class, 'period'])->whereNumber('id');
            Route::get('regular-expenses/{id}/history', [Regular::class, 'history'])->whereNumber('id');
            Route::post('regular-expenses/{id}/post', [Regular::class, 'post'])->whereNumber('id');
            Route::get('lookup/{resource}', [M::class, 'listing'])->where('resource', 'contacts|items');
            Route::get('documents/{type}', [B::class, 'documents'])->name('documents.index');
            Route::post('documents/{type}', [B::class, 'save'])->name('documents.store');
            Route::post('documents/{type}/drafts', [B::class, 'save'])->name('documents.drafts.store');
            Route::get('document/{document}', [B::class, 'show'])->whereNumber('document')->name('documents.show');
            Route::patch('document/{document}/draft', [B::class, 'updateDraft'])->name('documents.drafts.update');
            Route::delete('document/{document}/draft', [B::class, 'deleteDraft'])->name('documents.drafts.destroy');
            Route::post('document/{document}/post', [B::class, 'postDraft'])->name('documents.post');
            Route::post('document/{document}/clone', [B::class, 'cloneDraft'])->name('documents.clone');
            Route::post('document/{document}/returns', [B::class, 'returns'])->name('documents.returns.store');
            Route::post('{source}/{id}/cancel', [B::class, 'cancel'])->where('source', 'document|payments|stock-adjustments')->whereNumber('id');
            Route::get('payments/preview', [B::class, 'paymentPreview']);
            Route::get('payments', [B::class, 'payments'])->name('payments.index');
            Route::post('payments', [B::class, 'payment'])->name('payments.store');
            Route::post('transfers', [B::class, 'payment'])->name('transfers.store');
            Route::get('stock-adjustments', [B::class, 'adjustments']);
            Route::post('stock-adjustments', [B::class, 'countStock']);
            Route::get('owner-money', [B::class, 'ownerList']);
            Route::post('owner-money', [B::class, 'owner']);
            Route::post('owner-money/{id}/cancel', [B::class, 'cancelOwner'])->whereNumber('id');
            Route::get('reports/{report}/export', [R::class, 'export']);
            Route::get('reports/{report}', [R::class, 'show']);
            Route::post('settings/opening-balances/finalize', [B::class, 'openings']);
            Route::post('settings/close-through', [B::class, 'close']);
            Route::match(['get', 'patch'], 'settings/business', [M::class, 'settings']);
            Route::get('settings/staff', [M::class, 'staff']);
            Route::post('settings/staff/invitations', [M::class, 'staff']);
            Route::patch('settings/staff/{user}', [M::class, 'membership'])->whereNumber('user');
            Route::post('settings/staff/invitations/{id}/revoke', [M::class, 'revokeInvitation'])->whereNumber('id');
            Route::post('attachments', [M::class, 'upload']);
            Route::get('attachments/{id}', [M::class, 'download'])->whereNumber('id');
            Route::get('audit', [M::class, 'audit']);
            Route::get('settings/{resource}', [M::class, 'listing'])->where('resource', 'accounts|expense-categories');
            Route::post('settings/{resource}', [M::class, 'save'])->where('resource', 'accounts|expense-categories');
            Route::post('settings/{resource}/{id}/{action}', [M::class, 'archive'])->where('resource', 'accounts|expense-categories')->where('action', 'archive|restore');
            Route::get('{resource}', [M::class, 'listing'])->where('resource', 'contacts|items');
            Route::post('{resource}', [M::class, 'save'])->where('resource', 'contacts|items');
            Route::get('{resource}/{id}', [M::class, 'show'])->where('resource', 'contacts|items')->whereNumber('id');
            Route::patch('{resource}/{id}', [M::class, 'save'])->where('resource', 'contacts|items')->whereNumber('id');
            Route::post('{resource}/{id}/{action}', [M::class, 'archive'])->where('resource', 'contacts|items')->whereNumber('id')->where('action', 'archive|restore');
        });
    });
});
Route::post('platform-auth/login', [P::class, 'login'])->middleware('throttle:5,1');
Route::middleware('auth:superadmin')->group(function () {
    Route::post('platform-auth/logout', [P::class, 'logout']);
    Route::get('api/platform/me', [P::class, 'me']);
    Route::get('api/platform/tenants', [P::class, 'tenants']);
    Route::patch('api/platform/tenants/{id}/access', [P::class, 'access'])->whereNumber('id');
});
