<?php

use App\Http\Controllers\BarcodeController as Barcodes;
use App\Http\Controllers\BasketController;
use App\Http\Controllers\BillingController;
use App\Http\Controllers\BusinessController as B;
use App\Http\Controllers\CatalogController as Catalog;
use App\Http\Controllers\FulfilmentController as Fulfilment;
use App\Http\Controllers\ImportController as Imports;
use App\Http\Controllers\MasterController as M;
use App\Http\Controllers\NotificationController;
use App\Http\Controllers\PackageController;
use App\Http\Controllers\PartyController as Party;
use App\Http\Controllers\PlatformController as P;
use App\Http\Controllers\PosController as Pos;
use App\Http\Controllers\RecurringExpenseController as Regular;
use App\Http\Controllers\ReportController as R;
use App\Http\Controllers\WorkflowController as Workflow;
use Illuminate\Support\Facades\Route;

Route::prefix('api')->middleware(['auth:sanctum', 'auth:tenant'])->group(function () {
    Route::get('me', [B::class, 'me']);
    Route::delete('notifications/devices/{id}', [NotificationController::class, 'revoke'])->whereNumber('id');
    Route::middleware('verified')->group(function () {
        Route::match(['get', 'patch'], 'notifications/preferences', [NotificationController::class, 'preferences'])->middleware('throttle:30,1');
        Route::get('notifications/devices', [NotificationController::class, 'devices']);
        Route::post('notifications/devices', [NotificationController::class, 'register'])->middleware('throttle:30,1');
        Route::get('billing/gateways', [BillingController::class, 'gateways']);
        Route::get('billing/accounts/{id}/payments', [BillingController::class, 'payments'])->whereNumber('id');
        Route::get('billing/accounts/{id}/businesses', [BillingController::class, 'businesses'])->whereNumber('id');
        Route::post('billing/accounts/{id}/checkout', [BillingController::class, 'checkout'])->whereNumber('id');
        Route::get('billing/accounts/{id}/payments/{reference}', [BillingController::class, 'payment'])->whereNumber('id')->whereUuid('reference');
        Route::post('billing/accounts/{id}/payments/{reference}/confirm', [BillingController::class, 'confirm'])->whereNumber('id')->whereUuid('reference');
        Route::get('billing/packages', [BillingController::class, 'packages']);
        Route::get('billing/accounts/{id}/subscription', [BillingController::class, 'subscription'])->whereNumber('id');
        Route::post('billing/accounts/{id}/trial', [BillingController::class, 'trial'])->whereNumber('id');
        Route::get('billing/accounts', [BillingController::class, 'index']);
        Route::post('billing/accounts', [BillingController::class, 'store']);
        Route::get('billing/accounts/{id}', [BillingController::class, 'show'])->whereNumber('id');
        Route::post('billing/accounts/{id}/businesses', [BillingController::class, 'business'])->whereNumber('id');
        Route::get('businesses', [B::class, 'businesses'])->name('businesses.index');
        Route::post('businesses', [B::class, 'createBusiness'])->name('businesses.store');
        Route::post('invitations/{token}', [M::class, 'acceptInvitation'])->name('invitations.accept');
        Route::prefix('app/{tenant}')->middleware('tenant.context')->name('app.')->group(function () {
            Route::get('/', [R::class, 'dashboard'])->name('dashboard');
            Route::get('lookup', [M::class, 'lookup']);
            Route::get('item-categories', [Catalog::class, 'categories']);
            Route::post('item-categories', [Catalog::class, 'category']);
            Route::patch('item-categories/{id}', [Catalog::class, 'category'])->whereNumber('id');
            Route::get('reorders', [Catalog::class, 'reorders']);
            Route::get('imports', [Imports::class, 'listing']);
            Route::post('imports/preview', [Imports::class, 'preview']);
            Route::post('imports', [Imports::class, 'apply']);
            Route::get('imports/{resource}/{mode}', [Imports::class, 'export'])->where('resource', 'contacts|items|price_lists')->where('mode', 'template|export');
            Route::get('collections', [Party::class, 'collections']);
            Route::get('followups', [Party::class, 'listing']);
            Route::post('followups', [Party::class, 'save']);
            Route::get('followups/{id}', [Party::class, 'show'])->whereNumber('id');
            Route::patch('followups/{id}', [Party::class, 'save'])->whereNumber('id');
            Route::match(['get', 'patch'], 'contacts/{id}/trading', [Party::class, 'trading'])->whereNumber('id');
            Route::match(['get', 'post'], 'contacts/{id}/rates', [Party::class, 'rates'])->whereNumber('id');
            Route::get('contacts/{id}/price-suggestions', [Party::class, 'suggestions'])->whereNumber('id');
            Route::get('price-suggestions', [Party::class, 'suggestions']);
            Route::match(['get', 'post'], 'basket-offers', [BasketController::class, 'offers']);
            Route::match(['get', 'patch'], 'basket-offers/{id}', [BasketController::class, 'offers'])->whereNumber('id');
            Route::match(['get', 'post'], 'price-lists', [Party::class, 'priceLists']);
            Route::match(['get', 'patch'], 'price-lists/{id}', [Party::class, 'priceLists'])->whereNumber('id');
            Route::patch('contacts/{id}/price-lists', [Party::class, 'assignLists'])->whereNumber('id');
            Route::get('workflows', [Workflow::class, 'listing']);
            Route::post('workflows', [Workflow::class, 'save']);
            Route::post('workflows/preview', [Workflow::class, 'preview']);
            Route::post('workflow/{id}/preview', [Workflow::class, 'preview'])->whereNumber('id');
            Route::get('workflow/{id}', [Workflow::class, 'show'])->whereNumber('id');
            Route::patch('workflow/{id}', [Workflow::class, 'save'])->whereNumber('id');
            Route::post('workflow/{id}/status', [Workflow::class, 'status'])->whereNumber('id');
            Route::post('workflow/{id}/order', [Workflow::class, 'order'])->whereNumber('id');
            Route::post('workflow/{id}/bill', [Workflow::class, 'bill'])->whereNumber('id');
            Route::post('workflow/{id}/fulfilments/preview', [Fulfilment::class, 'preview'])->whereNumber('id');
            Route::post('workflow/{id}/fulfilments', [Fulfilment::class, 'save'])->whereNumber('id');
            Route::post('workflow/{id}/staged-bills/preview', [Fulfilment::class, 'billPreview'])->whereNumber('id');
            Route::post('workflow/{id}/staged-bills', [Fulfilment::class, 'bill'])->whereNumber('id');
            Route::post('workflow/{id}/ordered-bills/preview', [Fulfilment::class, 'orderedPreview'])->whereNumber('id');
            Route::post('workflow/{id}/ordered-bills', [Fulfilment::class, 'orderedBill'])->whereNumber('id');
            Route::post('workflow/{id}/billed-fulfilments/preview', [Fulfilment::class, 'billedPreview'])->whereNumber('id');
            Route::post('workflow/{id}/billed-fulfilments', [Fulfilment::class, 'billedSave'])->whereNumber('id');
            Route::get('fulfilment/{id}', [Fulfilment::class, 'show'])->whereNumber('id');
            Route::post('fulfilment/{id}/cancel', [Fulfilment::class, 'cancel'])->whereNumber('id');
            Route::post('workflow/{id}/packages/preview', [Fulfilment::class, 'packPreview'])->whereNumber('id');
            Route::post('workflow/{id}/packages', [Fulfilment::class, 'pack'])->whereNumber('id');
            Route::get('package/{id}', [Fulfilment::class, 'packageShow'])->whereNumber('id');
            Route::post('package/{id}/ship/preview', [Fulfilment::class, 'shipPreview'])->whereNumber('id');
            Route::post('package/{id}/ship', [Fulfilment::class, 'ship'])->whereNumber('id');
            Route::post('package/{id}/deliver/preview', [Fulfilment::class, 'deliveryPreview'])->whereNumber('id');
            Route::post('package/{id}/deliver', [Fulfilment::class, 'deliver'])->whereNumber('id');
            Route::post('package/{id}/undo-delivery', [Fulfilment::class, 'undoDelivery'])->whereNumber('id');
            Route::post('package/{id}/cancel', [Fulfilment::class, 'cancelPackage'])->whereNumber('id');
            Route::get('pos/config', [Pos::class, 'config']);
            Route::get('barcodes/config', [Barcodes::class, 'config']);
            Route::get('barcodes/items', [Barcodes::class, 'labelItems']);
            Route::post('barcodes/labels', [Barcodes::class, 'labels']);
            Route::patch('barcodes/config', [Barcodes::class, 'configure']);
            Route::post('pos/scan', [Barcodes::class, 'scan']);
            Route::post('barcodes/items/{id}', [Barcodes::class, 'item'])->whereNumber('id');
            Route::patch('pos/profile', [Pos::class, 'profile']);
            Route::post('pos/branches', [Pos::class, 'branch']);
            Route::post('pos/resources', [Pos::class, 'resource']);
            Route::patch('pos/resources/{id}', [Pos::class, 'resource'])->whereNumber('id');
            Route::post('pos/preview', [Pos::class, 'preview']);
            Route::post('pos/sales', [Pos::class, 'sale']);
            Route::get('restaurant/orders', [Pos::class, 'orders']);
            Route::post('restaurant/orders', [Pos::class, 'order']);
            Route::post('restaurant/orders/{id}/send', [Pos::class, 'send'])->whereNumber('id');
            Route::post('restaurant/orders/{id}/tickets/{ticket}', [Pos::class, 'ticket'])->whereNumber('id')->whereNumber('ticket');
            Route::post('restaurant/orders/{id}/cancel', [Pos::class, 'cancelOrder'])->whereNumber('id');
            Route::post('restaurant/orders/{id}/checkout', [Pos::class, 'orderCheckout'])->whereNumber('id');
            Route::post('restaurant/orders/{id}/checkout/preview', [Pos::class, 'orderPreview'])->whereNumber('id');
            Route::get('appointments', [Pos::class, 'bookings']);
            Route::post('appointments', [Pos::class, 'booking']);
            Route::post('appointments/{id}', [Pos::class, 'updateBooking'])->whereNumber('id');
            Route::post('appointments/{id}/checkout', [Pos::class, 'bookingCheckout'])->whereNumber('id');
            Route::post('appointments/{id}/checkout/preview', [Pos::class, 'bookingPreview'])->whereNumber('id');
            Route::get('regular-expenses', [Regular::class, 'listing']);
            Route::post('regular-expenses', [Regular::class, 'save']);
            Route::get('regular-expenses/{id}', [Regular::class, 'show'])->whereNumber('id');
            Route::patch('regular-expenses/{id}', [Regular::class, 'save'])->whereNumber('id');
            Route::get('regular-expenses/{id}/period', [Regular::class, 'period'])->whereNumber('id');
            Route::get('regular-expenses/{id}/history', [Regular::class, 'history'])->whereNumber('id');
            Route::post('regular-expenses/{id}/post', [Regular::class, 'post'])->whereNumber('id');
            Route::get('lookup/{resource}', [M::class, 'listing'])->where('resource', 'contacts|items');
            Route::get('documents/{type}', [B::class, 'documents'])->name('documents.index');
            Route::post('documents/{type}', [B::class, 'save'])->name('documents.store');
            Route::post('documents/{type}/drafts', [B::class, 'save'])->name('documents.drafts.store');
            Route::post('documents/{type}/preview', [B::class, 'preview']);
            Route::post('document/{document}/draft/preview', [B::class, 'draftPreview'])->whereNumber('document');
            Route::post('document/{document}/post/preview', [B::class, 'postPreview'])->whereNumber('document');
            Route::get('document/{document}', [B::class, 'show'])->whereNumber('document')->name('documents.show');
            Route::patch('document/{document}/draft', [B::class, 'updateDraft'])->name('documents.drafts.update');
            Route::delete('document/{document}/draft', [B::class, 'deleteDraft'])->name('documents.drafts.destroy');
            Route::post('document/{document}/post', [B::class, 'postDraft'])->name('documents.post');
            Route::post('document/{document}/clone', [B::class, 'cloneDraft'])->name('documents.clone');
            Route::post('document/{document}/returns', [B::class, 'returns'])->name('documents.returns.store');
            Route::post('document/{document}/returns/preview', [B::class, 'returnPreview'])->name('documents.returns.preview');
            Route::post('{source}/{id}/cancel', [B::class, 'cancel'])->where('source', 'document|payments|stock-adjustments')->whereNumber('id');
            Route::get('payments/preview', [B::class, 'paymentPreview']);
            Route::get('payments', [B::class, 'payments'])->name('payments.index');
            Route::post('payments', [B::class, 'payment'])->name('payments.store');
            Route::post('transfers', [B::class, 'payment'])->name('transfers.store');
            Route::get('stock-adjustments', [B::class, 'adjustments']);
            Route::post('stock-adjustments', [B::class, 'countStock']);
            Route::get('owner-money', [B::class, 'ownerList']);
            Route::post('owner-money', [B::class, 'owner']);
            Route::post('owner-money/{id}/cancel', [B::class, 'cancelOwner'])->whereNumber('id');
            Route::get('reports/{report}/export', [R::class, 'export']);
            Route::get('reports/{report}', [R::class, 'show']);
            Route::post('settings/opening-balances/finalize', [B::class, 'openings']);
            Route::post('settings/close-through', [B::class, 'close']);
            Route::match(['get', 'patch'], 'settings/business', [M::class, 'settings']);
            Route::get('settings/staff', [M::class, 'staff']);
            Route::post('settings/staff/invitations', [M::class, 'staff']);
            Route::patch('settings/staff/{user}', [M::class, 'membership'])->whereNumber('user');
            Route::post('settings/staff/invitations/{id}/revoke', [M::class, 'revokeInvitation'])->whereNumber('id');
            Route::post('attachments', [M::class, 'upload']);
            Route::get('attachments/{id}', [M::class, 'download'])->whereNumber('id');
            Route::get('audit', [M::class, 'audit']);
            Route::get('settings/{resource}', [M::class, 'listing'])->where('resource', 'accounts|expense-categories');
            Route::post('settings/{resource}', [M::class, 'save'])->where('resource', 'accounts|expense-categories');
            Route::post('settings/{resource}/{id}/{action}', [M::class, 'archive'])->where('resource', 'accounts|expense-categories')->where('action', 'archive|restore');
            Route::get('{resource}', [M::class, 'listing'])->where('resource', 'contacts|items');
            Route::post('{resource}', [M::class, 'save'])->where('resource', 'contacts|items');
            Route::get('{resource}/{id}', [M::class, 'show'])->where('resource', 'contacts|items')->whereNumber('id');
            Route::patch('{resource}/{id}', [M::class, 'save'])->where('resource', 'contacts|items')->whereNumber('id');
            Route::post('{resource}/{id}/{action}', [M::class, 'archive'])->where('resource', 'contacts|items')->whereNumber('id')->where('action', 'archive|restore');
        });
    });
});
Route::post('platform-auth/login', [P::class, 'login'])->middleware('throttle:5,1');
Route::middleware('auth:superadmin')->group(function () {
    Route::post('platform-auth/logout', [P::class, 'logout']);
    Route::get('api/platform/me', [P::class, 'me']);
    Route::get('api/platform/packages', [PackageController::class, 'index']);
    Route::post('api/platform/packages', [PackageController::class, 'save']);
    Route::patch('api/platform/packages/{id}', [PackageController::class, 'save'])->whereNumber('id');
    Route::get('api/platform/tenants', [P::class, 'tenants']);
    Route::patch('api/platform/tenants/{id}/access', [P::class, 'access'])->whereNumber('id');
});
