import { IonButton } from '@ionic/react';
import { useState } from 'react';
import { Link, useLocation } from 'react-router-dom';
import { useWorkspace } from '../lib/context';
import { send, useData, useOnline, useSave } from '../lib/api';
import type { Page } from '../lib/types';
import EntrySteps from '../components/EntrySteps';
import { Check, Empty, Errors, Field, Heading, Loading, OptionalDetails, Select, Submit } from '../components/ui';
import { Pagination } from './Records';

interface Problem {column:string;message:string}
interface ImportRow {row:number;id:string|null;name:string;action:'create'|'update';category:string|null;errors:Problem[];changes:{column:string;before:unknown;after:unknown}[]}
interface Preview {headers:string[];mapping:string[];columns:string[];headerErrors:Problem[];rows:ImportRow[];categories:string[];ignored:string[];counts:{create:number;update:number;categories:number};valid:boolean;digest:string|null;version:string}
interface Batch {id:string;resource:string;created_count:number;updated_count:number;category_count:number;created_at:string}

export default function Imports() {
  const {base,path,revision,changed,t}=useWorkspace();const location=useLocation();const [resource,setResource]=useState<'items'|'contacts'|'price_lists'>(()=>{const value=new URLSearchParams(location.search).get('resource');return value==='items'||value==='price_lists'?value:'contacts';});
  const [replaceRules,setReplaceRules]=useState(false);const [csv,setCsv]=useState('');const [mapping,setMapping]=useState<string[]>();const [review,setReview]=useState<{data:Preview;signature:string}>();const [busy,setBusy]=useState(false);const [error,setError]=useState<Error>();const [result,setResult]=useState<Batch>();const [rowPage,setRowPage]=useState(1);const [historyPage,setHistoryPage]=useState(1);const [fileReset,setFileReset]=useState(0);const form=useSave();const online=useOnline();const history=useData<Page<Batch>>(`${base}/imports?page=${historyPage}`,revision);
  const input={resource,csv,...(resource==='price_lists'?{replace_rules:replaceRules}:{}),...(mapping?{mapping}:{})};const signature=JSON.stringify(input);const preview=review?.data;const fresh=review?.signature===signature;const ready=!!preview?.valid&&!!preview.digest&&fresh;const locked=form.busy||form.uncertain||busy;
  function source(value:string){setCsv(value);if(csv.split(/\r?\n/,1)[0]!==value.split(/\r?\n/,1)[0])setMapping(undefined);setReview(undefined);setError(undefined);setResult(undefined);setRowPage(1);form.clear();}
  async function fileSelected(file?:File){if(!file)return;setBusy(true);setError(undefined);try{if(file.size>1048576)throw new Error(t('Use UTF-8 CSV up to 1 MiB.'));const text=new TextDecoder('utf-8',{fatal:true}).decode(await file.arrayBuffer());source(text);}catch(cause){setError(cause instanceof Error?cause:new Error(t('Could not read CSV.')));}finally{setBusy(false);}}
  async function previewCsv(){if(locked||!csv.trim())return;setBusy(true);setError(undefined);form.clear();try{const response=await send<{data:Preview}>(base+'/imports/preview',input);setReview({data:response.data,signature});setRowPage(1);}catch(cause){setError(cause as Error);setReview(undefined);}finally{setBusy(false);}}
  function mapColumn(index:number,value:string){const next=mapping?[...mapping]:preview!.mapping.map(column=>preview!.columns.includes(column)?column:'__unmapped');next[index]=value;setMapping(next);form.clear();}
  function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();if(!ready||!preview)return;void form.save<Batch>(base+'/imports',{...input,digest:preview.digest,version:preview.version},batch=>{setResult(batch);setCsv('');setMapping(undefined);setReview(undefined);setFileReset(n=>n+1);setHistoryPage(1);changed();});}
  function columnLabel(column:string){const labels:Record<string,string>={id:'List ID',name:'List name',channel:'Price for',pricing_scheme:'Quantity pricing method',enabled:'Enabled',adjustment_mode:'Standard price adjustment',adjustment_percent:'Percentage',starts_bs:'Start day (BS)',ends_bs:'End day (BS)',item_id:'Item ID',item_sku:'SKU (optional)',item_name:'Name',min_qty:'Minimum quantity',price:'Unit price (NPR)',unit_snapshot:'Unit',pos_unit:'Billed base unit',item_kind:'Item type',rules:'Item prices / tiers'};return resource==='price_lists'?t(labels[column]||column.replaceAll('_',' ')):column.replaceAll('_',' ');}
  function value(text:unknown):string{if(text===null||text===undefined)return '—';if(typeof text==='boolean')return t(text?'Yes':'No');if(resource==='price_lists'&&typeof text==='string'&&['sale','purchase','increase','decrease','slab','volume'].includes(text))return t(({sale:'Sales',purchase:'Purchases',increase:'Increase',decrease:'Decrease',slab:'Slab',volume:'Volume'} as Record<string,string>)[text]);if(resource==='price_lists'&&Array.isArray(text))return text.length?text.map(rule=>`${rule.item_name||rule.item_id} · ${t('Minimum quantity')}: ${rule.min_qty} ${rule.unit_snapshot} · ${t('Unit price (NPR)')}: ${rule.price}`).join('; '):t('No price rules');return typeof text==='object'?JSON.stringify(text):String(text);}
  return <><Heading title={t('Import CSV')} description={t('Preview first. Apply all rows together; errors leave existing records unchanged.')}><Link to={path+'/'+(resource==='price_lists'?'price-lists':resource)}>{t(resource==='price_lists'?'Price lists':resource==='items'?'Items':'Parties')}</Link></Heading>
    {result&&<div className="notice" role="status">{t('Import saved')} #{result.id} · {t('Created')}: {result.created_count} · {t('Updated')}: {result.updated_count} · {t('Categories')}: {result.category_count}</div>}
    <EntrySteps key={fileReset} labels={[t('CSV source'),t('Columns & errors'),t('Review & apply')]} dirty={!!csv} busy={locked} error={form.error||error} canContinue={[!!preview&&fresh,!busy&&ready]} t={t} onSubmit={submit}>
      <div className="form-main"><Errors error={error||form.error}/>{form.uncertain&&<IonButton disabled={form.busy} onClick={()=>void form.retry()}>{t('Retry original action')}</IonButton>}
        <section className="panel" data-entry-step="0"><h2>{t('CSV source')}</h2><fieldset disabled={locked} className="import-fields" aria-label={t('CSV source')}><Select label={t('Import type')} value={resource} onChange={next=>{setResource(next as 'items'|'contacts'|'price_lists');setMapping(undefined);setReview(undefined);setError(undefined);setResult(undefined);form.clear();}}><option value="contacts">{t('Parties')}</option><option value="items">{t('Items')}</option><option value="price_lists">{t('Price lists')}</option></Select><div className="detail-actions"><a download href={`${base}/imports/${resource}/template`}>{t('Download template')}</a><a download href={`${base}/imports/${resource}/export`}>{t('Export existing records')}</a></div><p>{t(resource==='price_lists'?'Repeat list ID or new list name/channel on every row. Item ID, SKU or exact name identifies each tier. Omitted details and tiers stay.':'Blank ID creates a record. Existing ID updates it. Omitted columns keep existing values; blank cells clear optional values.')}</p>{resource==='price_lists'&&<><Check checked={replaceRules} onChange={next=>{setReplaceRules(next);form.clear();}}>{t('Replace tiers for included lists')}</Check><p>{t(replaceRules?'All existing tiers in included lists will be replaced. Metadata-only rows clear tiers. Review before/after rules.':'Merge matching item/minimum tiers; keep omitted tiers.')}</p></>}<Field label={t('Choose CSV file')}><input key={fileReset} type="file" accept=".csv,text/csv" onChange={event=>void fileSelected(event.target.files?.[0])}/></Field><Field label={t('CSV text')}><textarea name="csv" rows={8} value={csv} maxLength={1048576} onChange={event=>source(event.target.value)} spellCheck={false}/></Field></fieldset>{mapping&&<IonButton fill="clear" disabled={locked} onClick={()=>{setMapping(undefined);setReview(undefined);setError(undefined);form.clear();}}>{t('Reset column mapping')}</IonButton>}<small>{t(resource==='price_lists'?'Up to 1000 rows / 50 lists / 1 MiB. Ten tiers per item. Quantities use billed base units; prices use NPR.':'Up to 500 data rows / 1 MiB. UTF-8, commas, decimal points. Four party roles can be combined.')}</small><IonButton fill="outline" disabled={locked||!online||!csv.trim()} onClick={()=>void previewCsv()}>{t(busy?'Previewing…':'Preview CSV')}</IonButton><p>{t('Stock and money balances use starting balances, stock counts or normal payments. CSV import changes master details only.')}</p></section>
        <section className="panel" data-entry-step="1"><h2>{t('Columns & errors')}</h2>{preview?<><p>{t('Map each CSV column once. Explicitly ignored columns are excluded from the import.')}</p><fieldset className="import-fields" disabled={locked}><div className="form-grid">{preview.headers.map((header,index)=><Select key={index} name={`mapping.${index}`} label={`${t('Column')}: ${header}`} value={mapping?.[index]??(preview.columns.includes(preview.mapping[index])?preview.mapping[index]:'__unmapped')} onChange={selected=>{if(!locked)mapColumn(index,selected);}}><option value="__unmapped">{t('Choose field')}</option><option value="">{t('Ignore column')}</option>{preview.columns.map(column=><option key={column} value={column}>{columnLabel(column)}</option>)}</Select>)}</div></fieldset><IonButton fill="outline" disabled={locked||!online} onClick={()=>void previewCsv()}>{t('Preview column mapping')}</IonButton>{!fresh&&<p role="status">{t('Import options changed. Preview again before applying.')}</p>}{preview.headerErrors.length>0&&<div className="error-box" role="alert">{preview.headerErrors.map((problem,index)=><p key={index}>{problem.column}: {problem.message}</p>)}</div>}{preview.rows.filter(row=>row.errors.length).map(row=><div key={row.row} className="error-box" role="alert"><strong>{t('Row')} {row.row} · {row.name}</strong>{row.errors.map((problem,index)=><p key={index}>{problem.column}: {problem.message}</p>)}</div>)}{fresh&&preview.valid&&<p>{t('All rows passed validation. Review changes before applying.')}</p>}</>:<p>{t('Choose a file or paste CSV, then preview it.')}</p>}</section>
      </div>
      <aside className="panel form-summary" data-entry-step="2"><h2>{t('Review & apply')}</h2>{resource==='price_lists'&&<p>{t('Counts refer to lists. All tier changes appear on the first row of each list.')}</p>}{preview?<><div className="import-counts"><span>{t('Created')}: <strong>{preview.counts.create}</strong></span><span>{t('Updated')}: <strong>{preview.counts.update}</strong></span><span>{t('Categories')}: <strong>{preview.counts.categories}</strong></span></div>{preview.categories.length>0&&<p>{t('New categories')}: {preview.categories.join(', ')}</p>}{preview.ignored.length>0&&<p className="error-box">{t('Ignored columns')}: {preview.ignored.join(', ')}</p>}{!ready&&<p>{t('Fix errors and preview current values before applying.')}</p>}{preview.rows.slice((rowPage-1)*25,rowPage*25).map(row=><article className="import-row" key={row.row}><strong>{t('Row')} {row.row} · {row.name||'—'}</strong><small>{t(row.action==='create'?'Create':'Update')}{row.id&&` · ID ${row.id}`}{row.category&&` · ${row.category}`}</small><OptionalDetails label={t('See changed fields')}>{row.changes.map((change,index)=><div className="import-change" key={index}><strong>{columnLabel(change.column)}</strong><span>{value(change.before)} → {value(change.after)}</span></div>)}{!row.changes.length&&<small>{t('No changed fields')}</small>}</OptionalDetails></article>)}<Pagination page={rowPage} pages={Math.ceil(preview.rows.length/25)} change={setRowPage}/><Submit busy={form.busy} disabled={locked||!ready}>{t('Apply reviewed import')}</Submit><p>{t('No bills, stock movements or payments are created. Keep export copies before bulk updates.')}</p></>:<p>{t('Preview CSV to see changes.')}</p>}</aside>
    </EntrySteps>
    <section className="panel section"><h2>{t('Import history')}</h2>{history.loading||history.error?<Loading error={history.error} retry={history.reload}/>:history.data?.data.length?<>{history.data.data.map(batch=><div className="mini-row" key={batch.id}><strong>#{batch.id} · {t(batch.resource==='price_lists'?'Price lists':resource==='items'?'Items':'Parties')}</strong><span>{t('Created')}: {batch.created_count} · {t('Updated')}: {batch.updated_count} · {t('Categories')}: {batch.category_count}</span><small>{batch.created_at}</small></div>)}<Pagination page={historyPage} pages={history.data.last_page} change={setHistoryPage}/></>:<Empty title={t('No imports yet')}/>}</section>
  </>;
}





