import { IonButton, IonContent, IonPage } from '@ionic/react';
import { useState } from 'react';
import { ApiError, request, resetSession, send, useData } from '../lib/api';
import type { Business, Page } from '../lib/types';
import { Errors, Field, Heading, Loading, Select, Status, Submit } from '../components/ui';
import Auth from './Auth';
import { Pagination } from './Records';

interface TenantRow extends Business { owner_email: string; staff_count: string; document_count: string }
export default function Platform() {
  const me = useData<{ data: { name: string } }>('/api/platform/me'); const [page,setPage] = useState(1); const [query,setQuery] = useState(''); const [revision,setRevision] = useState(0); const rows = useData<Page<TenantRow>>(me.data ? `/api/platform/tenants?page=${page}&q=${encodeURIComponent(query)}` : null, revision); const [selected,setSelected] = useState<TenantRow>(); const [status,setStatus] = useState('active'); const [until,setUntil] = useState(''); const [reason,setReason] = useState(''); const [password,setPassword] = useState(''); const [busy,setBusy] = useState(false); const [error,setError] = useState<Error>();
  if (me.loading) return <IonPage><IonContent><Loading /></IonContent></IonPage>;
  if (!me.data) return me.error && (!(me.error instanceof ApiError) || me.error.status !== 401) ? <IonPage><IonContent><Loading error={me.error} retry={me.reload} /></IonContent></IonPage> : <Auth admin reload={me.reload} />;
  return <IonPage><IonContent><div className="platform-wrap"><header className="businesses-header"><span className="brand"><span className="brand-mark">b</span>businessbook <span className="badge active">platform</span></span><IonButton fill="clear" onClick={async () => { await request('/platform-auth/logout', { method: 'POST' }); resetSession(); me.reload(); }}>Sign out</IonButton></header><Heading eyebrow="PLATFORM ADMINISTRATION" title="Business access" description="Manage access dates and status. Financial records require tenant membership." /><Field label="Search businesses" value={query} onChange={e => { setPage(1); setQuery(e.target.value); }} /><section className="panel">{rows.loading || rows.error ? <Loading error={rows.error} retry={rows.reload} /> : rows.data?.data.map(row => <div className="platform-row" key={row.id}><div><strong>{row.name}</strong><small>{row.owner_email}</small><small>{row.staff_count} staff · {row.document_count} documents</small></div><Status value={row.access_status} /><span>{row.access_until || row.trial_ends_at || 'No expiry'}</span><IonButton fill="outline" onClick={() => { setSelected(row); setStatus(row.access_status); const expiry = row.access_until || row.trial_ends_at; const date = expiry ? new Date(expiry) : undefined; setUntil(date ? new Date(date.getTime() - date.getTimezoneOffset() * 60000).toISOString().slice(0,16) : ''); }}>Manage access</IonButton></div>)}{rows.data && <Pagination page={page} pages={rows.data.last_page} change={setPage} />}</section>{selected && <form className="panel narrow-form section" onSubmit={async e => { e.preventDefault(); setBusy(true); setError(undefined); try { await send(`/api/platform/tenants/${selected.id}/access`, { access_status: status, access_until: until ? new Date(until).toISOString() : null, reason,password }, 'PATCH'); setSelected(undefined); setPassword(''); setRevision(n => n + 1); } catch (error) { setError(error as Error); } finally { setBusy(false); } }}><h2>{selected.name}</h2><Errors error={error} /><Select label="Access status" value={status} onChange={setStatus}>{['trial','active','expired','suspended'].map(value => <option value={value} key={value}>{value}</option>)}</Select><Field label="Access until (local time)" type="datetime-local" value={until} onChange={e => setUntil(e.target.value)} /><Field label="Reason" value={reason} onChange={e => setReason(e.target.value)} minLength={5} required /><Field label="Confirm admin password" type="password" autoComplete="current-password" value={password} onChange={e => setPassword(e.target.value)} required /><Submit busy={busy}>Update access</Submit></form>}</div></IonContent></IonPage>;
}
