// Labels shared by product, offer and scale setup; conversion factors stay in Laravel.
export const measurementUnits: Record<string, string> = {
  unit: 'Piece / unit',
  pair: 'Pair',
  dozen: 'Dozen',
  kg: 'Kilogram (kg)',
  g: 'Gram (g)',
  mg: 'Milligram (mg)',
  tonne: 'Metric tonne (t)',
  lb: 'Pound (lb)',
  oz: 'Ounce (oz)',
  l: 'Litre (L)',
  ml: 'Millilitre (mL)',
  cl: 'Centilitre (cL)',
  us_gal: 'US gallon (gal US)',
  imp_gal: 'Imperial gallon (gal UK)',
  mm: 'Millimetre (mm)',
  cm: 'Centimetre (cm)',
  m: 'Metre (m)',
  in: 'Inch (in)',
  ft: 'Foot (ft)',
  yd: 'Yard (yd)',
  sq_mm: 'Square millimetre (mm²)',
  sq_cm: 'Square centimetre (cm²)',
  sq_m: 'Square metre (m²)',
  sq_in: 'Square inch (in²)',
  sq_ft: 'Square foot (ft²)',
  sq_yd: 'Square yard (yd²)',
  cu_mm: 'Cubic millimetre (mm³)',
  cu_cm: 'Cubic centimetre (cm³)',
  cu_m: 'Cubic metre (m³)',
  cu_in: 'Cubic inch (in³)',
  cu_ft: 'Cubic foot (ft³)',
  cu_yd: 'Cubic yard (yd³)',
  board_ft: 'Board foot (bd ft)',
};
export const measurementUnitGroups: Record<string, string[]> = {
  Count: ['unit', 'pair', 'dozen'],
  Weight: ['kg', 'g', 'mg', 'tonne', 'lb', 'oz'],
  'Liquid volume': ['l', 'ml', 'cl', 'us_gal', 'imp_gal'],
  Length: ['mm', 'cm', 'm', 'in', 'ft', 'yd'],
  Area: ['sq_mm', 'sq_cm', 'sq_m', 'sq_in', 'sq_ft', 'sq_yd'],
  'Cubic volume': ['cu_mm', 'cu_cm', 'cu_m', 'cu_in', 'cu_ft', 'cu_yd', 'board_ft'],
};
export const measurementUnitLabel = (code: string) =>
  measurementUnits[code] || code.replaceAll('_', ' ');
