export interface User { id: string; name: string; email: string; email_verified_at: string | null; locale: 'en' | 'ne' }
export interface Business { pos_profile?: string; parent_tenant_id?: string | null; id: string; slug: string; name: string; role: string; opening_finalized_at: string | null; opening_date_bs: number | null; closed_through_bs: number | null; access_status: string; access_until: string | null; trial_ends_at: string | null; default_locale: 'en' | 'ne'; address: string | null; phone: string | null; pan: string | null; tax_recording_enabled: boolean; default_tax_bps: string }
export interface Party { id: string; name: string; phone: string | null; is_customer: boolean; is_supplier: boolean; is_employee: boolean; is_rent: boolean; is_system: boolean; receivable_paisa?: string; payable_paisa?: string; email?: string; address?: string; pan?: string; archived_at?: string | null }
export interface Item { pos_unit?: string; pos_methods?: string[] | null; pos_custom_units?: {label:string;qty:string}[] | null; service_minutes?: number; id: string; name: string; sku: string | null; kind: 'stock' | 'service'; unit_label: string; sale_price_paisa: string; last_purchase_price_paisa?: string | null; qty_milli: string; value_paisa?: string; low_stock_qty_milli: string; default_tax_bps: string; default_tax_category: string; archived_at?: string | null }
export interface Account { id: string; name: string; system_key: string | null; balance_paisa?: string; money_kind?: string }
export interface Category { id: string; name: string; account_id: string }
export interface Lookup { contacts: Party[]; items: Item[]; accounts: Account[]; categories: Category[]; channels?: { receivables_id: string; payables_id: string } }
export interface DocLine { measurement_snapshot?: Record<string,unknown> | null; id: string; item_id: string | null; expense_category_id: string | null; description: string; unit_snapshot: string; qty_milli: string; unit_price_paisa: string; line_discount_paisa: string; net_base_paisa: string; total_paisa: string; tax_paisa: string; tax_bps: string; tax_category: string; inventory_cost_paisa?: string; returnable_qty_milli: string }
export interface Payment { id: string; kind: string; status: string; amount_paisa: string; business_date_bs: number; reference?: string | null }
export interface Doc { id: string; type: string; status: string; version: number; number: string | null; business_date_bs: number; contact_id: string; total_paisa: string; subtotal_paisa: string; invoice_discount_paisa: string; line_discount_paisa: string; tax_paisa: string; due_paisa: string; credit_paisa: string; net_settled_paisa: string; notes: string | null; party_snapshot: Party; business_snapshot: Business; cancellation_reason?: string; cancellation_date_bs?: number; lines: DocLine[]; payments: Payment[]; returns: Doc[]; attachments: { id: string; original_name: string }[] }
export interface Page<T> { data: T[]; current_page: number; last_page: number; total: number }
export interface Workflow { id:string; kind:'quote'|'sales_order'|'purchase_order'; number:string; status:string; version:number; niche:string; title?:string|null; reference?:string|null; specifications?:string|null; notes?:string|null; cancellation_reason?:string|null; business_date_bs:number; due_date_bs?:number|null; valid_until_bs?:number|null; contact_id:string; party_snapshot:Party; business_snapshot:Business; lines:DocLine[]; subtotal_paisa:string; line_discount_paisa:string; invoice_discount_paisa:string; tax_paisa:string; total_paisa:string; source_id?:string|null; child_id?:string|null; document_id?:string|null; bill_status?:string|null; expired:boolean; overdue:boolean }
export interface Overview { bank_overdrafts_paisa: string; cash_paisa: string; inventory_paisa: string; receivables_paisa: string; payables_paisa: string; sales_paisa: string; cogs_paisa: string; profit_paisa: string; customer_credits_paisa: string; supplier_advances_paisa: string; assets_paisa: string; liabilities_paisa: string; equity_paisa: string; debit_paisa: string; credit_paisa: string }
export interface Dashboard extends Overview { today_bs: number; role: string; tenant: Business; recent: Doc[]; low_stock: Item[] }
